package exceptiondemo2;


import java.io.IOException;

public class Child extends Parent{
	
		public void m1() throws IOException{
		
		System.out.println("inside parent m1");
	}
}
